module.exports = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  TOKEN: 'TOKEN',
  ERROR: 'ERROR',
  AUTHENTICATE: 'AUTHENTICATE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SEND_MESSAGE: 'SEND_MESSAGE',
  GET_MESSAGE: 'GET_MESSAGE',
  GET_CHAT_HISTORY: 'GET_CHAT_HISTORY',
  SET_CHAT_HISTORY: 'SET_CHAT_HISTORY',
  SOCKET_RENEWED: 'SOCKET_RENEWED',
  SOCKET_REFRESH: 'SOCKET_REFRESH',
};
